name: Build & Test new feature

on:
  push:
    branches:
    - main
    - feature/*
    
jobs:
  build:
    name: Build libraries
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: 18
